# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

onedTVw_c <- function(y, lambda) {
    .Call(`_RSCC_onedTVw_c`, y, lambda)
}

ProxG_dfs_w <- function(y, X, Xty, sample_order_list, edge_weight_list, var_weight, intercept, B_initial, lambda_row, lambda_col, lambda_tau, B_save, GIC_out, MSE_out, var_num, step_size = 1, tol = 0.0000001, MaxIt = 100) {
    .Call(`_RSCC_ProxG_dfs_w`, y, X, Xty, sample_order_list, edge_weight_list, var_weight, intercept, B_initial, lambda_row, lambda_col, lambda_tau, B_save, GIC_out, MSE_out, var_num, step_size, tol, MaxIt)
}

GIC_dpsw_c <- function(y, X, sample_order_list, edge_weight_list, var_weight, intercept, lambda_row_list, lambda_col_list, lambda_tau_list, step_size = 1, tol = 0.0000001, MaxIt = 100) {
    .Call(`_RSCC_GIC_dpsw_c`, y, X, sample_order_list, edge_weight_list, var_weight, intercept, lambda_row_list, lambda_col_list, lambda_tau_list, step_size, tol, MaxIt)
}

onedTV_c <- function(y, lambda) {
    .Call(`_RSCC_onedTV_c`, y, lambda)
}

ProxG_dfs <- function(y, X, Xty, sample_order_list0, penalty_factor, intercept, B_initial, lambda_row, lambda_col, lambda_tau, B_save, GIC_out, MSE_out, var_num, step_size = 1, tol = 0.0000001, MaxIt = 100) {
    .Call(`_RSCC_ProxG_dfs`, y, X, Xty, sample_order_list0, penalty_factor, intercept, B_initial, lambda_row, lambda_col, lambda_tau, B_save, GIC_out, MSE_out, var_num, step_size, tol, MaxIt)
}

MSE_dfs_c <- function(y, X, sample_order_list0, penalty_factor, intercept, lambda_row_list, lambda_col_list, lambda_tau_list, min_var, step_size = 1, tol = 0.0000001, MaxIt = 100) {
    .Call(`_RSCC_MSE_dfs_c`, y, X, sample_order_list0, penalty_factor, intercept, lambda_row_list, lambda_col_list, lambda_tau_list, min_var, step_size, tol, MaxIt)
}

